INSERT INTO countries (country_code, country_name, country_name_native, language_code, flag_emoji, enabled) VALUES
('AD','Andorra','Andorra','en','🇦🇩',true),
('AE','United Arab Emirates','United Arab Emirates','en','🇦🇪',true),
('AF','Afghanistan','Afghanistan','en','🇦🇫',true),
('AG','Antigua and Barbuda','Antigua and Barbuda','en','🇦🇬',true),
('AL','Albania','Albania','en','🇦🇱',true),
('AM','Armenia','Armenia','en','🇦🇲',true),
('AO','Angola','Angola','en','🇦🇴',true),
('AR','Argentina','Argentina','en','🇦🇷',true),
('AT','Austria','Austria','en','🇦🇹',true),
('AU','Australia','Australia','en','🇦🇺',true),
('AZ','Azerbaijan','Azerbaijan','en','🇦🇿',true),
('BA','Bosnia and Herzegovina','Bosnia and Herzegovina','en','🇧🇦',true),
('BB','Barbados','Barbados','en','🇧🇧',true),
('BD','Bangladesh','Bangladesh','en','🇧🇩',true),
('BE','Belgium','Belgium','en','🇧🇪',true),
('BF','Burkina Faso','Burkina Faso','en','🇧🇫',true),
('BG','Bulgaria','Bulgaria','en','🇧🇬',true),
('BH','Bahrain','Bahrain','en','🇧🇭',true),
('BI','Burundi','Burundi','en','🇧🇮',true),
('BJ','Benin','Benin','en','🇧🇯',true),
('BN','Brunei','Brunei','en','🇧🇳',true),
('BO','Bolivia','Bolivia','en','🇧🇴',true),
('BR','Brazil','Brazil','en','🇧🇷',true),
('BS','Bahamas','Bahamas','en','🇧🇸',true),
('BT','Bhutan','Bhutan','en','🇧🇹',true),
('BW','Botswana','Botswana','en','🇧🇼',true),
('BY','Belarus','Belarus','en','🇧🇾',true),
('BZ','Belize','Belize','en','🇧🇿',true),
('CA','Canada','Canada','en','🇨🇦',true),
('CD','DR Congo','DR Congo','en','🇨🇩',true),
('CF','Central African Republic','Central African Republic','en','🇨🇫',true),
('CG','Congo','Congo','en','🇨🇬',true),
('CH','Switzerland','Switzerland','en','🇨🇭',true),
('CI','Ivory Coast','Ivory Coast','en','🇨🇮',true),
('CL','Chile','Chile','en','🇨🇱',true),
('CM','Cameroon','Cameroon','en','🇨🇲',true),
('CN','China','China','en','🇨🇳',true),
('CO','Colombia','Colombia','en','🇨🇴',true),
('CR','Costa Rica','Costa Rica','en','🇨🇷',true),
('CU','Cuba','Cuba','en','🇨🇺',true),
('CV','Cape Verde','Cape Verde','en','🇨🇻',true),
('CY','Cyprus','Cyprus','en','🇨🇾',true),
('CZ','Czechia','Czechia','en','🇨🇿',true),
('DE','Germany','Germany','en','🇩🇪',true),
('DJ','Djibouti','Djibouti','en','🇩🇯',true),
('DK','Denmark','Denmark','en','🇩🇰',true),
('DM','Dominica','Dominica','en','🇩🇲',true),
('DO','Dominican Republic','Dominican Republic','en','🇩🇴',true),
('DZ','Algeria','Algeria','en','🇩🇿',true),
('EC','Ecuador','Ecuador','en','🇪🇨',true),
('EE','Estonia','Estonia','en','🇪🇪',true),
('EG','Egypt','Egypt','en','🇪🇬',true),
('EH','Western Sahara','Western Sahara','en','🇪🇭',true),
('ER','Eritrea','Eritrea','en','🇪🇷',true),
('ES','Spain','Spain','en','🇪🇸',true),
('ET','Ethiopia','Ethiopia','en','🇪🇹',true),
('FI','Finland','Finland','en','🇫🇮',true),
('FJ','Fiji','Fiji','en','🇫🇯',true),
('FM','Micronesia','Micronesia','en','🇫🇲',true),
('FR','France','France','en','🇫🇷',true),
('GA','Gabon','Gabon','en','🇬🇦',true),
('GB','United Kingdom','United Kingdom','en','🇬🇧',true),
('GD','Grenada','Grenada','en','🇬🇩',true),
('GE','Georgia','Georgia','en','🇬🇪',true),
('GH','Ghana','Ghana','en','🇬🇭',true),
('GL','Greenland','Greenland','en','🇬🇱',true),
('GM','Gambia','Gambia','en','🇬🇲',true),
('GN','Guinea','Guinea','en','🇬🇳',true),
('GQ','Equatorial Guinea','Equatorial Guinea','en','🇬🇶',true),
('GR','Greece','Greece','en','🇬🇷',true),
('GT','Guatemala','Guatemala','en','🇬🇹',true),
('GW','Guinea-Bissau','Guinea-Bissau','en','🇬🇼',true),
('GY','Guyana','Guyana','en','🇬🇾',true),
('HK','Hong Kong','Hong Kong','en','🇭🇰',true),
('HN','Honduras','Honduras','en','🇭🇳',true),
('HR','Croatia','Croatia','en','🇭🇷',true),
('HT','Haiti','Haiti','en','🇭🇹',true),
('HU','Hungary','Hungary','en','🇭🇺',true),
('ID','Indonesia','Indonesia','en','🇮🇩',true),
('IE','Ireland','Ireland','en','🇮🇪',true),
('IL','Israel','Israel','en','🇮🇱',true),
('IN','India','India','en','🇮🇳',true),
('IQ','Iraq','Iraq','en','🇮🇶',true),
('IR','Iran','Iran','en','🇮🇷',true),
('IS','Iceland','Iceland','en','🇮🇸',true),
('IT','Italy','Italy','en','🇮🇹',true),
('JM','Jamaica','Jamaica','en','🇯🇲',true),
('JO','Jordan','Jordan','en','🇯🇴',true),
('JP','Japan','Japan','en','🇯🇵',true),
('KE','Kenya','Kenya','en','🇰🇪',true),
('KG','Kyrgyzstan','Kyrgyzstan','en','🇰🇬',true),
('KH','Cambodia','Cambodia','en','🇰🇭',true),
('KI','Kiribati','Kiribati','en','🇰🇮',true),
('KM','Comoros','Comoros','en','🇰🇲',true),
('KN','Saint Kitts and Nevis','Saint Kitts and Nevis','en','🇰🇳',true),
('KR','South Korea','South Korea','en','🇰🇷',true),
('KW','Kuwait','Kuwait','en','🇰🇼',true),
('KZ','Kazakhstan','Kazakhstan','en','🇰🇿',true),
('LA','Laos','Laos','en','🇱🇦',true),
('LB','Lebanon','Lebanon','en','🇱🇧',true),
('LC','Saint Lucia','Saint Lucia','en','🇱🇨',true),
('LI','Liechtenstein','Liechtenstein','en','🇱🇮',true),
('LK','Sri Lanka','Sri Lanka','en','🇱🇰',true),
('LR','Liberia','Liberia','en','🇱🇷',true),
('LS','Lesotho','Lesotho','en','🇱🇸',true),
('LT','Lithuania','Lithuania','en','🇱🇹',true),
('LU','Luxembourg','Luxembourg','en','🇱🇺',true),
('LV','Latvia','Latvia','en','🇱🇻',true),
('LY','Libya','Libya','en','🇱🇾',true),
('MA','Morocco','Morocco','en','🇲🇦',true),
('MC','Monaco','Monaco','en','🇲🇨',true),
('MD','Moldova','Moldova','en','🇲🇩',true),
('ME','Montenegro','Montenegro','en','🇲🇪',true),
('MG','Madagascar','Madagascar','en','🇲🇬',true),
('MH','Marshall Islands','Marshall Islands','en','🇲🇭',true),
('MK','North Macedonia','North Macedonia','en','🇲🇰',true),
('ML','Mali','Mali','en','🇲🇱',true),
('MM','Myanmar','Myanmar','en','🇲🇲',true),
('MN','Mongolia','Mongolia','en','🇲🇳',true),
('MR','Mauritania','Mauritania','en','🇲🇷',true),
('MT','Malta','Malta','en','🇲🇹',true),
('MU','Mauritius','Mauritius','en','🇲🇺',true),
('MV','Maldives','Maldives','en','🇲🇻',true),
('MW','Malawi','Malawi','en','🇲🇼',true),
('MX','Mexico','Mexico','en','🇲🇽',true),
('MY','Malaysia','Malaysia','en','🇲🇾',true),
('MZ','Mozambique','Mozambique','en','🇲🇿',true),
('NA','Namibia','Namibia','en','🇳🇦',true),
('NE','Niger','Niger','en','🇳🇪',true),
('NG','Nigeria','Nigeria','en','🇳🇬',true),
('NI','Nicaragua','Nicaragua','en','🇳🇮',true),
('NL','Netherlands','Netherlands','en','🇳🇱',true),
('NO','Norway','Norway','en','🇳🇴',true),
('NP','Nepal','Nepal','en','🇳🇵',true),
('NR','Nauru','Nauru','en','🇳🇷',true),
('NZ','New Zealand','New Zealand','en','🇳🇿',true),
('OM','Oman','Oman','en','🇴🇲',true),
('PA','Panama','Panama','en','🇵🇦',true),
('PE','Peru','Peru','en','🇵🇪',true),
('PG','Papua New Guinea','Papua New Guinea','en','🇵🇬',true),
('PH','Philippines','Philippines','en','🇵🇭',true),
('PK','Pakistan','Pakistan','en','🇵🇰',true),
('PL','Poland','Poland','en','🇵🇱',true),
('PS','Palestine','Palestine','en','🇵🇸',true),
('PT','Portugal','Portugal','en','🇵🇹',true),
('PW','Palau','Palau','en','🇵🇼',true),
('PY','Paraguay','Paraguay','en','🇵🇾',true),
('QA','Qatar','Qatar','en','🇶🇦',true),
('RO','Romania','Romania','en','🇷🇴',true),
('RS','Serbia','Serbia','en','🇷🇸',true),
('RU','Russia','Russia','en','🇷🇺',true),
('RW','Rwanda','Rwanda','en','🇷🇼',true),
('SA','Saudi Arabia','Saudi Arabia','en','🇸🇦',true),
('SB','Solomon Islands','Solomon Islands','en','🇸🇧',true),
('SC','Seychelles','Seychelles','en','🇸🇨',true),
('SD','Sudan','Sudan','en','🇸🇩',true),
('SE','Sweden','Sweden','en','🇸🇪',true),
('SG','Singapore','Singapore','en','🇸🇬',true),
('SI','Slovenia','Slovenia','en','🇸🇮',true),
('SK','Slovakia','Slovakia','en','🇸🇰',true),
('SL','Sierra Leone','Sierra Leone','en','🇸🇱',true),
('SM','San Marino','San Marino','en','🇸🇲',true),
('SN','Senegal','Senegal','en','🇸🇳',true),
('SO','Somalia','Somalia','en','🇸🇴',true),
('SR','Suriname','Suriname','en','🇸🇷',true),
('SS','South Sudan','South Sudan','en','🇸🇸',true),
('ST','São Tomé and Príncipe','São Tomé and Príncipe','en','🇸🇹',true),
('SV','El Salvador','El Salvador','en','🇸🇻',true),
('SY','Syria','Syria','en','🇸🇾',true),
('SZ','Eswatini','Eswatini','en','🇸🇿',true),
('TD','Chad','Chad','en','🇹🇩',true),
('TG','Togo','Togo','en','🇹🇬',true),
('TH','Thailand','Thailand','en','🇹🇭',true),
('TJ','Tajikistan','Tajikistan','en','🇹🇯',true),
('TL','Timor-Leste','Timor-Leste','en','🇹🇱',true),
('TM','Turkmenistan','Turkmenistan','en','🇹🇲',true),
('TN','Tunisia','Tunisia','en','🇹🇳',true),
('TO','Tonga','Tonga','en','🇹🇴',true),
('TR','Turkey','Turkey','en','🇹🇷',true),
('TT','Trinidad and Tobago','Trinidad and Tobago','en','🇹🇹',true),
('TV','Tuvalu','Tuvalu','en','🇹🇻',true),
('TW','Taiwan','Taiwan','en','🇹🇼',true),
('TZ','Tanzania','Tanzania','en','🇹🇿',true),
('UA','Ukraine','Ukraine','en','🇺🇦',true),
('UG','Uganda','Uganda','en','🇺🇬',true),
('US','United States','United States','en','🇺🇸',true),
('UY','Uruguay','Uruguay','en','🇺🇾',true),
('UZ','Uzbekistan','Uzbekistan','en','🇺🇿',true),
('VA','Vatican City','Vatican City','en','🇻🇦',true),
('VC','Saint Vincent and the Grenadines','Saint Vincent and the Grenadines','en','🇻🇨',true),
('VE','Venezuela','Venezuela','en','🇻🇪',true),
('VN','Vietnam','Vietnam','en','🇻🇳',true),
('VU','Vanuatu','Vanuatu','en','🇻🇺',true),
('WS','Samoa','Samoa','en','🇼🇸',true),
('XK','Kosovo','Kosovo','en','🇽🇰',true),
('XX','International','International','en','🇽🇽',true),
('YE','Yemen','Yemen','en','🇾🇪',true),
('ZA','South Africa','South Africa','en','🇿🇦',true),
('ZM','Zambia','Zambia','en','🇿🇲',true),
('ZW','Zimbabwe','Zimbabwe','en','🇿🇼',true)
ON CONFLICT (country_code) DO UPDATE SET country_name=EXCLUDED.country_name, country_name_native=EXCLUDED.country_name_native, flag_emoji=EXCLUDED.flag_emoji, updated_at=NOW();
